---
- hosts: localhost
  connection: local
  become: yes

  tasks:
#    - name: Wait 300 seconds, but only start checking after 60 seconds
#      # example from https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_connection_module.html#examples
#      wait_for_connection:
#        delay: 60
#        timeout: 300

    - name: Ensure apt is updated
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure essential tools are installed
      apt:
        pkg:
          - nano
          - wget
          - net-tools
          - mlocate
          - openjdk-11-jre-headless
          - git

    - name: add jenkins key for apt
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: add jenkins repository
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: make sure apt is updated with jenkins repo
      apt:
        name: "*"
        state: latest

    - name: install jenkins
      apt:
        pkg:
          - jenkins

    - name: enable jenkins to start when vm is rebooted
      # Using example from https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes

    - name: ensure jenkins is started
      # Using example from https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes
        state: started