pipeline {
  agent any
  stages {
    stage('Test Deploy Nginx') {
      steps {
        sh '''cd product/kubernetes
              pwd
              ls -lahrt
              echo $PWD
              echo "---------------------------------"
              kubectl delete pods --all -n cne
              kubectl apply -f $PWD/namespace.yaml
              kubectl apply -f $PWD/nginx-conf.yaml
              kubectl apply -f $PWD/nginx-lb.yaml -f $PWD/nginx.yaml
              kubectl describe service nginx-lb -n cne
'''
      }
    }

  }
}