apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginx-config
  namespace: cne
data: 
  default.conf: 
    server {
        listen 80;
        location / {
            proxy_pass http://google.com;
        }
    }