pipeline {
  agent any
  stages {
    stage('Pre-Staging') {
      steps {
        sh 'pwd'
        sh 'ls -lahrt'
        sh 'ls -lahrt infrastructure/pytest_vm'
      }
    }

    stage('Terraform Deploy') {
      steps {
        sh '''cd infrastructure/pytest_vm
terraform init
terraform plan
terraform apply --auto-approve'''
      }
    }

  }
}