---
- hosts: "localhost"

  tasks:
    - name: build & push backend image
      community.docker.docker_image:
        build:
          path: ./backend
        name: sashumi/cne_backend
        tag: v1
        push: yes

    - name: build & push frontend image
      community.docker.docker_image:
        build:
          path: ./frontend
        name: sashumi/cne_frontend
        tag: v1
        push: yes

    - name: build & push database image
      community.docker.docker_image:
        build:
          path: ./database
        name: sashumi/cne_database
        tag: v1
        push: yes
