---
- hosts: "10.10.1.181"

  tasks:
    # I am planning to use Jenkins-Dockerhub plugin to push images
    # https://github.com/jenkinsci/dockerhub-notification-plugin/blob/master/README.md
    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html#examples
    - name: copy dockerfile to remote host
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
      tags:
        - image_test

    - name: run backend unit test
      ansible.builtin.command: docker exec backend bash -c "pytest tests/ --cov application"
      tags:
        - image_test

    - name: run frontend unit test
      ansible.builtin.command: docker exec frontend bash -c "pytest tests/ --cov application"
      tags:
        - image_test