---
- hosts: "localhost"

  tasks:
    # I am planning to use Jenkins-Dockerhub plugin to push images
    # https://github.com/jenkinsci/dockerhub-notification-plugin/blob/master/README.md
    - name: build & push backend image
      community.docker.docker_image:
        build:
          path: ./backend
        name: sashumi/cne_backend
        tag: latest
        push: yes

    - name: build & push frontend image
      community.docker.docker_image:
        build:
          path: ./frontend
        name: sashumi/cne_frontend
        tag: latest
        push: yes

    - name: build & push database image
      community.docker.docker_image:
        build:
          path: ./database
        name: sashumi/cne_database
        tag: latest
        push: yes
