---
- hosts: "10.10.1.181"
  remote_user: "ubuntu"
  tasks:
    - name: copy docker compose file to pytest host
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
      tags:
        - image_test

    - name: run docker compose to bring up the combination
      ansible.builtin.command: cd /home/ubuntu &&  docker-compose up -d
      tags:
        - image_test

    - name: Sleep for 30 seconds to allow mysql script execution
      wait_for:
        timeout: 30

    - name: run backend unit test
      ansible.builtin.command: docker exec backend bash -c "pytest tests/ --cov application"
      tags:
        - image_test

    - name: Sleep for 30 seconds before frontend test
      wait_for:
        timeout: 30

    - name: run frontend unit test
      ansible.builtin.command: docker exec frontend bash -c "pytest tests/ --cov application"
      tags:
        - image_test

    - name: bring down docker compose set up
      ansible.builtin.command: cd /home/ubuntu && docker-compose down --rmi all --remove-orphans
      tags:
        - image_test