---
- hosts: "localhost"

  tasks:
    # I am planning to use Jenkins-Dockerhub plugin to push images
    # https://github.com/jenkinsci/dockerhub-notification-plugin/blob/master/README.md
    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html#examples
    - name: build & push backend image
      community.docker.docker_image:
        build:
          path: ./backend
        name: sashumi/cne_backend
        tag: latest
        source: build
        push: yes

    - name: build & push frontend image
      community.docker.docker_image:
        build:
          path: ./frontend
        name: sashumi/cne_frontend
        tag: latest
        source: build
        push: yes

    - name: build & push database image
      community.docker.docker_image:
        build:
          path: ./database
        name: sashumi/cne_database
        tag: latest
        source: build
        push: yes