pipeline {
  agent any
  stages {
    stage('Build images') {
      steps {
        sh '''cd product
              ansible-playbook image_creator.yml --tags build'''
      }
    }

    stage('Perform local testing ') {
      steps {
        sh '''docker exec backend bash -c "pytest tests/ --cov application"'''
      }
    }

    stage('Push images to dockerhub') {
      steps {
        sh '''mkdir -p ~/.docker
            aws s3 cp s3://shamsi-project2/keys/docker-auth-config.json ~/.docker/config.json
            ansible-playbook image_creator.yml --tags push'''
      }
    }
  }
}