pipeline {
  agent any
  stages {
    stage('Push Test Images to DockerHub') {
      steps {
        sh '''#Setup docker credentials + push test images
            mkdir -p ~/.docker
            aws s3 cp s3://shamsi-project2/keys/docker-auth-config.json ~/.docker/config.json
            cd product
            ansible-playbook image_creator.yml --tags image_test'''
      }
    }

    stage('pyTest DockerHub Test Images') {
      steps {
        sh '''cd product
              # downloading rsa key from secure s3 bucket to working directory
              aws s3 cp s3://shamsi-project2/keys/id_rsa .
              chmod 0600 id_rsa

              # skipping host fingerprint checking to avoid disruption
              export ANSIBLE_HOST_KEY_CHECKING=False

              # perform pre-execution cleanup
              ansible-playbook -i test_inventory \
                image_tester.yml\
                --tags image_test_cleanup \
                --private-key id_rsa

              # perform docker-compose up and testing
              ansible-playbook -i test_inventory \
                image_tester.yml\
                --tags image_test \
                --private-key id_rsa'''
      }
    }

    stage('Tag & Push Latest Images to DockerHub') {
      steps {
        sh '''#Setup docker credentials + publish images
              mkdir -p ~/.docker
              aws s3 cp s3://shamsi-project2/keys/docker-auth-config.json ~/.docker/config.json
              cd product
              ansible-playbook image_creator.yml --tags publish_image'''
      }
    }
  }
}