pipeline {
  agent any
  stages {
    stage('Build images') {
      steps {
        sh '''cd product
              ansible-playbook image_builder.yml'''
      }
    }

    stage('Perform local testing ') {
      steps {
        sh 'echo "this is where I test using docker compose on pytest vm"'
      }
    }

    stage('Push images to dockerhub') {
      steps {
        sh 'echo "this is where i push image to dockerhub" '
      }
    }

    stage('Deploy to EKS') {
      steps {
        sh 'echo "This where I use kubectl to deploy to EKS"'
      }
    }

  }
}